### ISSUE TITLE
Crash in pYs mods

### ISSUE THREAD

**Issue by mikelat** [DarkShadow44/resourcehighlighter-dark#20]
![image](https://user-images.githubusercontent.com/14167635/213883909-4b6cdd59-fd66-42b8-b271-f3216c160b71.png)

Using primarily pYs mods, attached save as well just incase.
[pY_mikelat.zip](https://github.com/DarkShadow44/resourcehighlighter-dark/files/10472859/pY_mikelat.zip)

**Comment by DarkShadow44** [comment]
Sorry, can't reproduce. Can you give me steps to cause that crash?

**Comment by mikelat** [comment]
Hey, I load my save with the latest version of resource highligher (the save may have it locked to a previous version), when I hit the shift H hotkey, I get a mod crash and that's the message I get.

Thanks for looking into it! Love the mod.

**Comment by DarkShadow44** [comment]
Thanks for the report, problem is py has stone with two products - stone and kerogen. Needed to rework the UI to show both at once. Please retest and report back, both for the crash and the new UI :smile:

**Comment by mikelat** [comment]
Thanks, its completely fixed! The only feedback I have for the UI is that some of the pY ores add a horizontal scrollbar to it, but its so minor compared to all the awesome featuers you added. Thank you!!

**Comment by ajklotz** [comment]
> Thanks for the report, problem is py has stone with two products - stone and kerogen. Needed to rework the UI to show both at once. Please retest and report back, both for the crash and the new UI 😄

It looks like the second column is what you're calling the All Results column. Should these buttons do anything? 
![image](https://user-images.githubusercontent.com/9448682/213898009-e29269f2-7dca-4145-8aeb-07f27fbacb84.png)

I dont think I'll ever see a resource with multiple types, of the same thing. In Mikelat's example, I guess he would see two types of stone, but wouldn't just clicking the stone icon in the first column just show the highlighted resources in the map anyway?

**Comment by DarkShadow44** [comment]
> It looks like the second column is what you're calling the All Results column. Should these buttons do anything?

Not directly, but you can hover them to see more details about the ore. You can't do that with the clickable button left, since that shows the resource entity itself.

> I dont think I'll ever see a resource with multiple types, of the same thing.

It is rare. Pyanodons has "stone" giving stone and kerogen, so you have two green buttons in the same row. But clickable is only the left most.
Pyanodons also has two sources of nickel ore - nickel ore patches and nickel reserves. Those give the same ore, but have a different (clickable) resource icon, so you can distinguish them.

Since I love py mods, I have to make sure to support those as well :grin:

**Comment by ajklotz** [comment]
I would argue that this column is as informational as the drills column you make optional in the mod settings. Since my experience in the game would never have multiple types of stone, or multiple types of oil, water, copper, etc, I would propose making this column an option like the drill to reduce how much data is shown in the UI?

**Comment by DarkShadow44** [comment]
Fair enough, I add a setting in the next version.
