### ISSUE TITLE
Chunk trimming not fixed

### ISSUE THREAD

**Issue by HentotheWen** [DarkShadow44/resourcehighlighter-dark#7]
[factorio-previous.log](https://github.com/DarkShadow44/resourcehighlighter-dark/files/6944435/factorio-previous.log)
See attached.

**Comment by BoomCaller** [comment]
I've got an identical error callstack.
On my save, I ran into this issue after deleting a couple surfaces and trimming a couple others.
I suspect your change only catches deleted surfaces, since trimmed surfaces are still valid.
Disabling your mod, saving the game, then re-enabling has resolved the issue.

**Comment by DarkShadow44** [comment]
Thanks for the report!
I pushed another fix. Can you please test if that fixes the issue.

**Comment by HentotheWen** [comment]
Will check when I get home, out of town for now.

**Comment by BoomCaller** [comment]
I can no longer get a crash by trimming chunks.

However, when I go to a new surface, then delete it, then open the highlighter gui, I get this callstack.
If I use "/rh_rescan" after deleting the new surface but before opening the gui, it does not crash and works as expected.
![image](https://user-images.githubusercontent.com/42724044/128647934-ebc3b861-5947-48b5-8177-9bbda4a63151.png)

**Comment by DarkShadow44** [comment]
Should be fixed now.
